services:
  backend_common:
    build: backend_api_honey/
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - storage/secrets/database.env
    depends_on:
      - db
    networks:
      - my_network

  db:
    build: storage/
    env_file:
      - storage/secrets/database.env
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    build:
      context: .
      dockerfile: pgadmin/Dockerfile
    env_file:
      - storage/secrets/database.env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - my_network


networks:
  my_network:


