name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        env:
          GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY_PATH }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            echo "Turning off containers."
            REPO_URL="git@github.com:shehram-tahir/honey_app.git"  # Replace with your repository URL
            DIR_NAME="honey_app"  # Replace with your desired director
            eval `ssh-agent -s`
            ssh-add ~/.ssh/$GIT_SSH_KEY
            if [ ! -d "$DIR_NAME" ]; then
              echo "Cloning $REPO_URL"
              git clone "$REPO_URL" --recursive -c submodule."honey_frontend".update=none "$DIR_NAME"
            else
              echo "Directory $DIR_NAME already exists. Skipping clone."            
            fi
            cd honey_app
            docker compose down
            git pull
            git submodule update --remote --recursive --merge &&
            git submodule foreach 'git checkout main && git pull origin main'
            echo "Repository cloned and submodules updated."
            docker compose up -d
