name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        env:  # Set environment variables
          VPS_SSH_KEY: '
-----BEGIN OPENSSH PRIVATE KEY-----\n
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBKhW5K3gjZIHFiRLzCrt8IA9oihiX/xV81VAVrOD2newAAAKB3ImOidyJj
ogAAAAtzc2gtZWQyNTUxOQAAACBKhW5K3gjZIHFiRLzCrt8IA9oihiX/xV81VAVrOD2new
AAAED3EZtG3byOrvlVUuVyRHIyyvpW0lnirgDi9EtiD1NiKEqFbkreCNkgcWJEvMKu3wgD
2iKGJf/FXzVUBWs4Pad7AAAAF3NoZWhyYW0udGFoaXJAZ21haWwuY29tAQIDBAUG\n
-----END OPENSSH PRIVATE KEY-----
'
        run: |
          echo $VPS_SSH_KEY | sed 's/./& /g'
          echo $VPS_HOST_VAR | sed 's/./& /g'
          echo 'HELLO' | sed 's/./& /g'
      - name: Set up SSH
        env: # Set environment variables
          VPS_SSH_KEY: '
-----BEGIN OPENSSH PRIVATE KEY

'
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: $VPS_SSH_KEY
      - name: Deploy to VPS
        env:  # Set environment variables
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          echo $VPS_SSH_KEY | sed 's/./& /g'
          echo $VPS_HOST | sed 's/./& /g'
          echo $VPS_USERNAME | sed 's/./& /g'
          ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST << 'EOF'
            echo "Turning off containers."
            docker compose down
            cd honey_app && git pull
            git submodule update --remote --recursive --merge &&
            git submodule foreach 'git checkout main && git pull origin main'
            echo "Repository cloned and submodules updated."
            docker compose up -d
          EOF
