name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VIVI_APP_SSH_KEY }}
          port: 22
          script: |
            REPO_URL="https://github.com/abdullahalhoothy/honey_app.git"
            DIR_NAME="honey_app"
            
            echo "Turning off containers."
            cd $DIR_NAME
            docker compose down
            echo "Docker compose down completed."
            
            cd ..
            rm -rf $DIR_NAME
            echo "Removed existing $DIR_NAME directory."
            
            docker image rm honey_app-backend_common

            echo "Cloning $REPO_URL"
            git clone "$REPO_URL" --recursive
            
            cd $DIR_NAME
            git pull
            git submodule update --remote --recursive --merge &&
            git submodule foreach 'git checkout main && git pull origin main'
            echo "Repository cloned and submodules updated."
            docker compose up -d

