name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VIVI_APP_SSH_KEY }}
          port: 22
          script: |
            echo "Turning off containers."
            REPO_URL="https://github.com/abdullahalhoothy/honey_app.git"
            DIR_NAME="honey_app"
            if [ ! -d "$DIR_NAME" ]; then
              echo "Cloning $REPO_URL"
              git clone "$REPO_URL" --recursive -c submodule."honey_frontend".update=none "$DIR_NAME"
            else
              echo "Directory $DIR_NAME already exists. Skipping clone."            
            fi
            cd honey_app
            docker compose down
            git pull
            git submodule update --remote --recursive --merge &&
            git submodule foreach 'git checkout main && git pull origin main'
            echo "Repository cloned and submodules updated."
            docker compose up -d

